version: '3'
services:
  mongo:
    container_name: mongo-container
    image: 'mongo:4'
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    environment:
      - MONGO_URL="mongodb://mongo:27017/clean-code-api"
  api:
    container_name: api-container
    build: .
    image: clean-code-api
    restart: always
    command: npm run debug:docker
    volumes:
      - ./dist/:/usr/src/clean-code-api/dist/
      - ./package.json:/usr/src/clean-code-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo
